### ISSUE TITLE
error when building v0.10

### ISSUE THREAD

**Issue by PuerkitoBio** [crack-lang/crack#1]
Hi,

Crack looks like a very interesting language, I'm trying to install it (0.10 tarball) on my Arch Linux laptop (amd64), I get the following error during `make`:

```
ext/Stub.cc: In member function 'const std::vector<crack::ext::Func*>& crack::ext::Type::getMethods() const':
ext/Stub.cc:103:24: internal compiler error: in expand_thunk, at cgraphunit.c:1700
 void Type::finish() { };
                         ^
```

I have installed llvm 3.3 from source, with the `make REQUIRES_RTTI=1` option.

Let me know if there's any additional info you'd want me to share.

Also, side-questions:

* Is that the correct repo to raise such issues? I saw the google code repo, but since google code will die soon I presumed this was the new home.
* Is that still actively developed? Kind of looks like a yes from the recent commits, but just want to be sure it's still a thing (I hope so, looks like there was a lot of work put in it already).
* I see that it is copyrighted Google, is it a 20% project? Or something Google-backed?

Thanks,
Martin

**Comment by mindhog** [comment]
So based on the "internal compiler error" I'm assuming that something in our code is causing your version of the compiler to choke.  Is your arch distro up-to-date?  If not, update it.  I'll try to reproduce this on an arch VM.

Offhand, I suggest you try some trivial transformations on the offending code: e.g. remove the unnecessary semicolon, add some more code below the line....

Ideally we should try to produce a minimal test case that reproduces the bug to send upstream to the gcc devs.

For the record, the answers to your other questions are at https://groups.google.com/forum/#!topic/crack-lang-dev/eNpvK-umJCg

**Comment by PuerkitoBio** [comment]
I found this: https://gcc.gnu.org/ml/gcc-bugs/2015-04/msg02314.html

I'll try downgrading gcc to an earlier version, as removing the semicolon did generate the same error.

**Comment by PuerkitoBio** [comment]
I installed gcc 4.8 and building the 0.10 tarball got all the way to the linker, but failed at link time. However, building from master worked, but `make check` did not (it looked for test/screen.bin`, while it looks like it should now use `test/screen`?). `make install` also fails, so looks like the build from source instructions mentioned here (`cd crack-language; ./bootstrap; ./configure; make; make check; sudo make install`, at https://code.google.com/p/crack-language/) are not up-to-date (or at least the autotools build isn't).

But in the end I now have a `crack` compiler, which is great! Time to start exploring :)

**Comment by PuerkitoBio** [comment]
Hm looks like I spoke too soon, I tried to rebuild after a `make clean` and it fails at the linker stage:

```
libtool: link: ( cd ".libs" && rm -f "compiler.la" && ln -s "../compiler.la" "compiler.la" )
../.libs/libCrackLang.so/.libs/libCrackLang.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
Makefile:1712: recipe for target 'crack' failed
make[1]: *** [crack] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:1718: recipe for target 'unittests' failed
```

**Comment by mindhog** [comment]
The linker failure does sound like a mixed build/library issue.  Regarding the test failure, I think you may be seeing a bug that went out with the 0.10 version of crackc. Can you try adding the -K (no-caching) option to the "crack" command in test/screen under where it echoes "rebuilding screen.bin..."?

**Comment by PuerkitoBio** [comment]
I would but I can't get it to build anymore, and I did a `make clean` so I don't have the compiler anymore. I think I'm sending a lot of false issues here, the basic problem being the gcc 5.1 ICE and not a crack issue, I believe (and the rest of my issues are very likely due to a bad mix of gcc versions). I'll close this and try to get setup using a Ubuntu docker image, don't lose more time on this, I'll reopen something if I encounter real crack issues (e.g. if the tests fail after a good build or something like that).

Thanks!
Martin
